name: dit
rot_type: ${rot_type}

d_model: 512
num_layers: 12
num_heads: 8
d_head: 64
dropout: 0.1

max_sequence_length: 100
use_learnable_pos_embedding: false

time_embed_dim: 1024
time_embed_mult: 4

use_adaptive_norm: true
use_text_condition: ${use_text_condition}
text_dropout_prob: 0.01
use_negative_prompts: ${use_negative_prompts}
use_object_mask: ${use_object_mask}
use_rgb: ${use_rgb}

attention_dropout: 0.1
cross_attention_dropout: 0.1

ff_mult: 4
ff_dropout: 0.1

backbone:
  name: pointnet2
  use_pooling: false
  layer1:
    npoint: 2048
    radius_list:
    - 0.04
    nsample_list:
    - 64
    mlp_list:
    - 4
    - 64
    - 64
    - 128
  layer2:
    npoint: 1024
    radius_list:
    - 0.1
    nsample_list:
    - 32
    mlp_list:
    - 128
    - 128
    - 128
    - 256
  layer3:
    npoint: 512
    radius_list:
    - 0.2
    nsample_list:
    - 32
    mlp_list:
    - 256
    - 128
    - 128
    - 256
  layer4:
    npoint: 128
    radius_list:
    - 0.3
    nsample_list:
    - 16
    mlp_list:
    - 256
    - 512
    - 512
  use_xyz: true
  normalize_xyz: true

gradient_checkpointing: false
use_flash_attention: true
attention_chunk_size: 512
memory_monitoring: false
max_batch_size: 32

enable_memory_efficient_attention: true
use_gradient_accumulation: false
memory_fraction: 0.9
