defaults:
  - backbone: pointnet2
  # - backbone: ptv3_light

name: dit
rot_type: ${rot_type}

d_model: 512
num_layers: 12
num_heads: 8
d_head: 64
dropout: 0.1

max_sequence_length: 100
use_learnable_pos_embedding: false

time_embed_dim: 1024
time_embed_mult: 4

use_adaptive_norm: true
use_text_condition: ${use_text_condition}
text_dropout_prob: 0.01
use_negative_prompts: ${use_negative_prompts}
use_object_mask: ${use_object_mask}
use_rgb: ${use_rgb}

attention_dropout: 0.1
cross_attention_dropout: 0.1

mmdit:
  enabled: false
  separate_modality_projections: true
  qkv_bias: false
  qk_norm: false
  modality_specific_adaln: false

ff_mult: 4
ff_dropout: 0.1

gradient_checkpointing: false
use_flash_attention: true
attention_chunk_size: 512
memory_monitoring: false
max_batch_size: 32

enable_memory_efficient_attention: true
use_gradient_accumulation: false
memory_fraction: 0.9
