name: degrasp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - pytorch-lightning=1.7.7
  - hydra-core=1.2.0
  - omegaconf=2.2.3
  - pip
  - pip:
    - wandb
    - h5py
    - scipy
    - trimesh
    - einops
    - tqdm
    - matplotlib
    - opencv-python
    # Note: pointnet2 is a local dependency and needs to be compiled separately.
    # Please refer to the project's documentation for instructions.
