defaults:
  - encoder: pointnet
  - decoder: mlp
  - criterion: loss
  - _self_

name: GraspCVAE
# latent_dim: &latent_dim 64
# encoder_out: &encoder_out 512
# condition_out: &condition_out 512
rot_type: ${rot_type}
mode: ${mode}
batch_size: ${batch_size}

optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 1.0e-4

scheduler:
  name: cosine
  t_max: ${epochs}
  min_lr: 1.0e-5