name: ptv3
use_pooling: false
grid_size: 0.02
in_channels: 6
max_context_points: 512

sampling_strategy: random

order:
  - "z"
  - "z-trans"

stride: [2, 2, 2, 2]
enc_depths: [2, 2, 2, 6, 2]
enc_channels: [32, 64, 128, 256, 512]
enc_num_head: [2, 4, 8, 16, 32]
enc_patch_size: [1024, 1024, 1024, 1024, 1024]

dec_depths: [2, 2, 2, 2]
dec_channels: [64, 64, 128, 256]
dec_num_head: [4, 4, 8, 16]
dec_patch_size: [1024, 1024, 1024, 1024]

mlp_ratio: 4
qkv_bias: true
attn_drop: 0.0
proj_drop: 0.0
drop_path: 0.1

enable_flash_attn: true
flash_attn_version: 2

shuffle_orders: false
