name: ptv3
variant: light
use_flash_attention: true
grid_size: 0.02  # 增大grid_size以减少token数量（从0.003->0.02，tokens: 8192->128左右）

# Encoder configuration (lightweight)
encoder_channels: [32, 64, 128, 256, 512]
encoder_depths: [1, 1, 2, 2, 1]
encoder_num_head: [2, 4, 8, 16, 16]
enc_patch_size: [1024, 1024, 1024, 1024, 1024]

# Decoder configuration (final output = decoder_channels[0])
decoder_channels: [512, 256, 128, 64] # [256,128,64,32]
decoder_depths: [1, 2, 1, 1]
dec_patch_size: [1024, 1024, 1024, 1024]

# MLP ratio
mlp_ratio: 2

# Output dimension (aligned with PointNet2, equals enc_channels[-1])
out_dim: 512

# Input feature channels beyond xyz (e.g., rgb=3). Default 1 for xyz-only.
input_feature_dim: 1

# Decoder attention heads per stage (optional override)
dec_num_head: [4, 4, 8, 16] # or  [2,4,8,8]

# Compatibility flags (align with PointNet2 interface)
use_xyz: true
normalize_xyz: true

#extremly light versiongrid_size: 0.02
# enc_channels: [16,32,64,128,256]
# enc_depths: [1,1,2,2,1]
# enc_num_head: [2,4,8,8,8]
# dec_channels: [256,128,64,32]
# dec_depths: [1,1,1,1]
# dec_num_head: [2,4,8,8]
# mlp_ratio: 2
# out_dim: 256
# input_feature_dim: 1