name: ptv3
variant: light
use_flash_attention: true
grid_size: 0.003

# Encoder configuration (lightweight)
encoder_channels: [32, 64, 128, 256, 512]
encoder_depths: [1, 1, 2, 2, 1]
encoder_num_head: [2, 4, 8, 16, 16]
enc_patch_size: [1024, 1024, 1024, 1024, 1024]

# Decoder configuration (final output = decoder_channels[0])
decoder_channels: [512, 256, 128, 64]
decoder_depths: [1, 2, 1, 1]
dec_patch_size: [1024, 1024, 1024, 1024]

# MLP ratio
mlp_ratio: 2

# Output dimension (aligned with PointNet2, equals enc_channels[-1])
out_dim: 512

# Compatibility flags (align with PointNet2 interface)
use_xyz: true
normalize_xyz: true

