name: ptv3
use_pooling: false
grid_size: 0.03
in_channels: 6
max_context_points: 256

sampling_strategy: random

order:
  - "z"
  - "z-trans"

stride: [2, 2, 2, 2]
enc_depths: [1, 1, 2, 2, 1]
enc_channels: [16, 32, 64, 128, 256]
enc_num_head: [1, 2, 4, 8, 16]
enc_patch_size: [512, 512, 512, 512, 512]

dec_depths: [1, 1, 1, 2]
dec_channels: [32, 32, 64, 128]
dec_num_head: [2, 2, 4, 8]
dec_patch_size: [512, 512, 512, 512]

mlp_ratio: 2
qkv_bias: true
attn_drop: 0.0
proj_drop: 0.0
drop_path: 0.05

enable_flash_attn: true
flash_attn_version: 2

shuffle_orders: false
