defaults:
  - /model/diffuser/decoder@decoder: dit
  - /model/diffuser/criterion@criterion: loss_standardized
  - _self_

name: GraspFlowMatcher
save_root: ${save_root}
device: cuda:0
rot_type: ${rot_type}
mode: ${mode}
print_freq: 250
batch_size: ${batch_size}

use_negative_prompts: ${use_negative_prompts}
use_object_mask: ${use_object_mask}
use_rgb: ${use_rgb}
fix_num_grasps: ${fix_num_grasps}
target_num_grasps: ${target_num_grasps}

flow_cfg:
  path_type: rectified
  diffusion:
    steps: 100
    schedule_cfg:
      beta:
        - 0.0001
        - 0.01
      beta_schedule: linear
      s: 0.008

ode_solver_cfg:
  method: dopri5
  n_steps: 20
  rtol: 1.0e-5
  atol: 1.0e-5

guidance_cfg:
  w: 0.0
  stable_guidance_type: cfg_zero_star
  zero_init_threshold: 0.1

optimizer:
  name: adamw
  lr: 1.0e-4
  weight_decay: 1.0e-3

scheduler:
  name: steplr
  step_size: 100
  step_gamma: 0.5
  t_max: 1000
  min_lr: 1.0e-5
