defaults:
  - _self_
  - model/diffuser@model: diffuser
  - data_cfg: sceneleapplus
  - distributed: default
  - wandb: default

epochs: 500
resume: False
save_root: &save_root ./experiments/exp
save_top_n: 5
seed: 42
rot_type: &rot_type r6d
mode: &mode camera_centric_scene_mean_normalized
batch_size: &batch_size 96
use_negative_prompts: &use_negative_prompts False
target_num_grasps: &target_num_grasps 64
fix_num_grasps: &fix_num_grasps True
use_object_mask: &use_object_mask True
use_rgb: &use_rgb False
exhaustive_sampling_strategy: &exhaustive_sampling_strategy interleaved

checkpoint_path: ???

trainer:
  max_epochs: ${epochs}
  accelerator: auto
  devices: auto
  strategy: auto
  precision: 32
  check_val_every_n_epoch: 5
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  benchmark: True
  log_every_n_steps: 20
  sync_batchnorm: False
  find_unused_parameters: True

hydra:
  output_subdir: null
  job:
    chdir: False
  hydra_logging:
    version: 1
    disable_existing_loggers: True
  job_logging:
    version: 1
    disable_existing_loggers: True
