enabled: auto
strategy: ddp
backend: nccl
devices: auto
num_nodes: 1
precision: 32
accumulate_grad_batches: 1
timeout: 1800
fallback_to_single_gpu: true
sync_batchnorm: true
find_unused_parameters: true
lr_scaling: sqrt
