defaults:
  # - decoder: unet
  - decoder: dit
  - criterion: loss_standardized
  - _self_

name: GraspDiffuser
save_root: ${save_root}
device: cuda:0
rot_type: ${rot_type}
mode: ${mode}
print_freq: 250
batch_size: ${batch_size}

steps: 100
pred_x0: true
rand_t_type: half

schedule_cfg:
  beta:
    - 0.0001
    - 0.01
  beta_schedule: linear
  s: 0.008

# optimizer:
#   name: adam
#   lr: 0.0001
#   weight_decay: 0.0001

# scheduler:
#   name: cosine
#   t_max: 1000
#   min_lr: 1.0e-05
optimizer:
  name: adamw
  lr: 0.0004
  weight_decay: 0.001
scheduler:
  name: steplr
  t_max: 1000
  min_lr: 1.0e-05
  step_size: 100
  step_gamma: 0.5

loss_type: l2
out_sigmoid: false
use_score: false
score_pretrain: false

fix_num_grasps: ${fix_num_grasps}
target_num_grasps: ${target_num_grasps}

use_cfg: false
guidance_scale: 7.5
use_negative_guidance: false
negative_guidance_scale: 1.0
use_negative_prompts: ${use_negative_prompts}
use_object_mask: ${use_object_mask}
use_rgb: ${use_rgb}

wandb_optimization:
  enable_visualization: false
  visualization_freq: 20
  log_histograms: false
  histogram_freq: 50
  monitor_system: false
  log_gradients: false
  gradient_freq: 1000
  system_freq: 500
