mode: ${mode}
device: 'cuda:0'
rot_type: ${rot_type}

hand_model:
  n_surface_points: 1024
  rot_type: ${rot_type}

loss_weights:
  translation: 20.0
  rotation: 20.0
  qpos: 1.0
  neg_loss: 0.0
  hand_chamfer: 1.0

use_negative_prompts: ${use_negative_prompts}

multi_grasp:
  loss_aggregation: "mean"
  use_consistency_loss: true
  consistency_loss_weight: 0.1
  diversity_loss_weight: 0.05

cost_weights:
  translation: 2.0
  rotation: 2.0
  qpos: 1.0

scale: 0.1
q1:
  lambda_torque: 10
  m: 8
  mu: 1
  nms: true
  thres_contact: 0.01
  thres_pen: 0.005
  thres_tpen: 0.01
  rot_type: ${rot_type}
