mode: ${mode}
device: 'cuda:0'
rot_type: ${rot_type}

hand_model:
  n_surface_points: 1024
  rot_type: ${rot_type}

loss_weights:
  translation: 20.0
  rotation: 20.0
  qpos: 1.0
  neg_loss: 0.0
  hand_chamfer: 1.0

standardized_validation_loss:
  enabled: true
  
  weights:
    translation: 10.0
    rotation: 10.0
    qpos: 5.0
    hand_chamfer: 2.0
    neg_loss: 0.0
  
  normalization:
    normalize_by_num_grasps: true
    normalize_by_batch_size: true
    use_sample_level_mean: true
  
  aggregation:
    strategy: "mean"
    ignore_invalid_grasps: true

use_negative_prompts: ${use_negative_prompts}

multi_grasp:
  loss_aggregation: "mean"
  use_consistency_loss: true
  consistency_loss_weight: 0.1
  diversity_loss_weight: 0.05

cost_weights:
  translation: 2.0
  rotation: 2.0
  qpos: 1.0


# # 线性升温（简单直接）
# set_loss:
#   schedule:
#     type: linear
#     start_weight: 0.0
#     final_weight: 0.5
# # 二次升温（更晚更强）
# set_loss:
#   schedule:
#     type: quadratic
#     start_weight: 0.0
#     final_weight: 0.6
# # 余弦降权（仅小 t 强，随 t 逐步减弱）
# set_loss:
#   schedule:
#     type: cosine
#     start_weight: 0.6
#     final_weight: 0.0

# set_loss:
#   enable: true
#   schedule:
#     type: none
#     final_weight: 0.001
# # 建议默认：余弦升温（后期更强，平滑）次保守
set_loss:
  enable: false
  schedule:
    type: cosine
    start_weight: 0.0
    final_weight: 0.001
  weights:
    cd: 1.0
    ot: 0.1
    repulsion: 0.0
  ot:
    eps: 0.05
    tau: 0.5
    iters: 50
    subsample: 256
  repulsion:
    k: 4
    s: 2.0
    delta: 1.0e-3
  cost_weights:
    translation: 2.0
    rotation: 2.0
    qpos: 0.1

set_metrics:
  enable: false
  cov_threshold: 0.2
  strict_cov_threshold: 0.1
  max_samples: 64 # 每个batch测试的抓取上限
  cost_weights:
    translation: 2.0
    rotation: 2.0
    qpos: 0.1
  log: # 是否开启metric计算
    cov: true
    mmd: true
    nnd: true
    component_stats: false

quality_metrics:
  enable: false
  metrics:
    penetration_penalty:
      enable: false
      weight: 1.0
    contact_quality:
      enable: false
      weight: 0.5

scale: 0.1

q1:
  lambda_torque: 10
  m: 8
  mu: 1
  nms: true
  thres_contact: 0.01
  thres_pen: 0.005
  thres_tpen: 0.01
  rot_type: ${rot_type}
