mode: ${mode}
device: 'cuda:0'
rot_type: ${rot_type}

hand_model:
  n_surface_points: 1024
  rot_type: ${rot_type}

loss_weights:
  translation: 20.0
  rotation: 20.0
  qpos: 1.0
  neg_loss: 0.0
  hand_chamfer: 1.0

standardized_validation_loss:
  enabled: true
  
  weights:
    translation: 10.0
    rotation: 10.0
    qpos: 5.0
    hand_chamfer: 2.0
    neg_loss: 0.0
  
  normalization:
    normalize_by_num_grasps: true
    normalize_by_batch_size: true
    use_sample_level_mean: true
  
  aggregation:
    strategy: "mean"
    ignore_invalid_grasps: true
  
  quality_metrics:
    include_penetration_penalty: false
    include_contact_quality: false
    penetration_weight: 1.0
    contact_weight: 0.5

use_negative_prompts: ${use_negative_prompts}

multi_grasp:
  loss_aggregation: "mean"
  use_consistency_loss: true
  consistency_loss_weight: 0.1
  diversity_loss_weight: 0.05

cost_weights:
  translation: 2.0
  rotation: 2.0
  qpos: 1.0

set_loss:
  enable: true
  schedule:
    type: none
    final_weight: 1.0
  weights:
    cd: 1.0
    ot: 0.0
    repulsion: 0.0
    phys: 0.0
  ot:
    eps: 0.05
    tau: 0.5
    iters: 50
    subsample: 256
  repulsion:
    k: 4
    s: 2.0
    delta: 1.0e-3
  cost_weights:
    translation: ${cost_weights.translation}
    rotation: ${cost_weights.rotation}
    qpos: ${cost_weights.qpos}

set_metrics:
  enable: true
  cov_threshold: 0.2
  max_samples: 256
  log:
    cov: true
    mmd: true
    nnd: true

scale: 0.1

q1:
  lambda_torque: 10
  m: 8
  mu: 1
  nms: true
  thres_contact: 0.01
  thres_pen: 0.005
  thres_tpen: 0.01
  rot_type: ${rot_type}
