defaults:
  - decoder: dit_fm
  - criterion: loss_standardized
  - _self_

name: GraspFlowMatching
save_root: ${save_root}
device: cuda:0
rot_type: ${rot_type}
mode: ${mode}  # 坐标系模式（camera_centric_scene_mean_normalized等）
print_freq: 250
batch_size: ${batch_size}

# Flow Matching specific configuration
fm:
  variant: rectified_flow  # rectified_flow | cfm | sfm
  path: linear_ot  # linear_ot | vp | ve
  continuous_time: true
  
  # Time sampling strategy
  t_sampler: uniform  # uniform | cosine | beta
  t_weight: null  # null | cosine | beta (for loss reweighting)
  
  # Noise distribution
  noise_dist: normal  # normal | custom
  
  # Stochastic Flow Matching (SFM) - for ablation
  sfm:
    sigma: 0.0  # Set > 0 to enable stochastic bridges
  
  # Optimal Transport Matching (集合到集合的最优配对)
  # 理论背景：对于无序集合数据（如1024个抓取），使用Sinkhorn算法
  # 计算最优传输配对，最小化总传输距离，让速度场更平滑、更易学习
  optimal_transport:
    enable: false  # 是否启用OT配对（默认关闭，可通过命令行覆盖）

    # Sinkhorn算法参数
    reg: 0.05  # 熵正则化参数（0.05-0.2）
              # 越小越接近真实OT（但收敛慢），越大收敛快（但略欠精确）
    num_iters: 50  # Sinkhorn迭代次数（50-100通常足够）

    # 距离度量
    distance_metric: euclidean  # euclidean | squared | weighted
                                # euclidean: L2距离
                                # squared: L2距离的平方（更强调远距离）
                                # weighted: 对pose不同组件加权（仅需配置component_weights，
                                #          切片按全局常量自动确定）

    # 组件加权配置（仅当distance_metric=weighted时使用）
    # 切片默认使用全局常量（utils/hand_model.py 中的 TRANSLATION_SLICE/QPOS_SLICE/ROTATION_SLICE），无需在配置中指定
    component_weights:
      translation: 1.0   # 平移权重（3D，单位：米）
      qpos: 0.0          # 关节角度权重（16维，单位：弧度）
      rotation: 2.0      # 旋转权重（6D rot6d 或其他表示）

    # 配对提取策略
    matching_strategy: greedy  # greedy | hungarian
                               # greedy: 快速，每行取最大值
                               # hungarian: 精确但需要scipy，慢

    # 数值稳定性
    normalize_cost: true  # 是否归一化代价矩阵到[0,1]

    # 训练策略
    start_epoch: 0  # 从第几个epoch开始使用OT（0=立即启用）
                    # 建议：可以先训练几个epoch稳定后再启用

    # 日志频率
    log_freq: 100  # 每多少个batch记录一次详细的OT统计信息

    # 混合耦合（Hybrid Coupling）控制：在OT噪声中注入部分独立噪声
    hybrid_coupling:
      enable: true      # 是否启用混合耦合（需在optimal_transport.enable为true时生效）
      beta: 0.2          # 噪声混合系数 β∈[0,1]，越大越接近独立耦合

# ODE Solver configuration
solver:
  type: rk4  # heun | rk4 | rk45
  nfe: 32  # Number of function evaluations (for fixed-step solvers)
  
  # Adaptive solver settings (for rk45)
  rtol: 1e-3
  atol: 1e-5
  max_step: 0.03125  # 1/32
  min_step: 1e-4
  max_nfe: 1000  # Maximum NFE for adaptive solver
  
  # Integration settings
  reverse_time: true  # Integrate from t=1 to t=0
  save_trajectories: false  # Save intermediate states for visualization

# Classifier-Free Guidance configuration
guidance:
  enable_cfg: false  # Enable CFG (set to false initially for stability)
  cond_drop_prob: 0.10  # Conditioning dropout probability during training
  scale: 3.0  # CFG scale (higher = stronger conditioning)
  
  # Stabilization techniques
  method: clipped  # basic | clipped | rescaled | adaptive
  diff_clip: 5.0  # Norm clipping threshold for (v_cond - v_uncond)
  pc_correction: false  # Enable predictor-corrector refinement
  dt_correction: 0.01  # Step size for predictor-corrector correction
  num_corrections: 1  # Number of correction iterations
  
  # Adaptive CFG settings (when method=adaptive)
  early_steps_scale: 0.0  # Scale for early timesteps
  late_steps_scale: 1.0  # Scale for late timesteps
  transition_point: 0.5  # Transition point (0 to 1)

# # Optimizer configuration
# optimizer:
#   name: adamw
#   lr: 0.0004
#   weight_decay: 0.001

# # Scheduler configuration
# scheduler:
#   name: steplr
#   t_max: 1000
#   min_lr: 1.0e-05
#   step_size: 100
#   step_gamma: 0.5
# Optimizer configuration
optimizer:
  name: adamw
  lr: 0.0004           # 保持高初始LR，以实现快速收敛
  weight_decay: 0.001

# Scheduler configuration
scheduler:
  name: cosine           # <-- 关键改动：使用余弦退火
  t_max: 500            # <-- 设为总 epoch 数
  min_lr: 1.0e-6         # <-- 衰减到的最低学习率
  step_size: null
  step_gamma: null
  # (step_size 和 step_gamma 是 steplr 专用的，cosine不需要)

# Debug and logging
debug:
  check_nan: true
  log_tensor_stats: false  # Set to true for detailed debugging
  print_freq: 50

# Compatibility settings
compat:
  keep_ddpm_interface: true  # Maintain interface compatibility with DDPM
  export_noise_like_keys: true  # Export v_pred as "pred_noise" for loss compatibility

# Grasp count control
fix_num_grasps: ${fix_num_grasps}
target_num_grasps: ${target_num_grasps}

# Conditioning flags
use_negative_prompts: ${use_negative_prompts}
use_object_mask: ${use_object_mask}
use_rgb: ${use_rgb}

# Loss configuration (reuse from diffuser)
loss_type: l2
out_sigmoid: false
use_score: false
score_pretrain: false

# WandB optimization (same as diffuser)
wandb_optimization:
  enable_visualization: false
  visualization_freq: 20
  log_histograms: false
  histogram_freq: 50
  monitor_system: false
  log_gradients: false
  gradient_freq: 1000
  system_freq: 500
