name: objectcentric
mode: object_centric  # 固定为object_centric模式

train:
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapUltra/data/1022_mini_succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  use_cached: false
  cache_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/cache/objectcentric
  cache_version: v1.0_objectcentric_mini
  cache_mode: train
  num_grasps: ${target_num_grasps}
  max_grasps_per_object: 256
  mesh_scale: 0.1
  max_points: 8192
  grasp_sampling_strategy: farthest_point
  use_exhaustive_sampling: true
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}
  object_sampling_ratio: 0.8
  table_size: 0.4
  batch_size: ${batch_size}
  num_workers: 16

val:
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapUltra/data/1025_mini_succ_collect_test
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  use_cached: false
  cache_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/cache/objectcentric
  cache_version: v1.0_objectcentric_mini
  cache_mode: val
  num_grasps: ${target_num_grasps}
  max_grasps_per_object: 256
  mesh_scale: 0.1
  max_points: 8192
  grasp_sampling_strategy: farthest_point
  use_exhaustive_sampling: true
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}
  object_sampling_ratio: 0.8
  table_size: 0.4
  batch_size: ${batch_size}
  num_workers: 16

test:
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapUltra/data/1025_mini_succ_collect_test
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  use_cached: false
  cache_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/cache/objectcentric
  cache_version: v1.0_objectcentric_mini
  cache_mode: test
  num_grasps: ${target_num_grasps}
  max_grasps_per_object: 256
  mesh_scale: 0.1
  max_points: 8192
  grasp_sampling_strategy: farthest_point
  use_exhaustive_sampling: true
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}
  object_sampling_ratio: 0.8
  table_size: 0.4
  batch_size: ${batch_size}
  num_workers: 16
