name: plussceneleap
mode: ${mode}
train:
  root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/test_final_test_520_1_processed
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  num_grasps: ${target_num_grasps}
  mode: ${mode}
  max_grasps_per_object: 1024
  mesh_scale: 0.1
  num_neg_prompts: 4
  enable_cropping: true
  max_points: 10000
  grasp_sampling_strategy: farthest_point
  # 穷尽采样配置 - 实现100%数据利用率
  use_exhaustive_sampling: true  # 启用穷尽采样
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}  # 推荐策略：每个chunk内FPS采样
  use_object_mask: ${use_object_mask}
  use_negative_prompts: ${use_negative_prompts}
  cache_version: v2.2_train  # 更新缓存版本以区分穷尽采样
  cache_mode: train
  batch_size: ${batch_size}
  num_workers: 16
val:
  root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/723_sub_15
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  num_grasps: ${target_num_grasps}
  mode: ${mode}
  max_grasps_per_object: 1024
  mesh_scale: 0.1
  num_neg_prompts: 4
  enable_cropping: true
  max_points: 10000
  grasp_sampling_strategy: farthest_point
  # 验证集可以选择不使用穷尽采样以保持一致性
  use_exhaustive_sampling: true  # 验证集使用传统采样
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}
  use_object_mask: ${use_object_mask}
  use_negative_prompts: ${use_negative_prompts}
  cache_version: v2.2_test  # 验证集使用不同的缓存版本
  cache_mode: test
  batch_size: ${batch_size}
  num_workers: 16
test:
  root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/723_sub_15
  succ_grasp_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeapPro/data/object/objaverse_v1/flat_models
  num_grasps: ${target_num_grasps}
  mode: ${mode}
  max_grasps_per_object: 1024
  mesh_scale: 0.1
  num_neg_prompts: 4
  enable_cropping: true
  max_points: 10000
  grasp_sampling_strategy: farthest_point
  # 测试集使用传统采样以保持评估一致性
  use_exhaustive_sampling: true  # 测试集使用传统采样
  exhaustive_sampling_strategy: ${exhaustive_sampling_strategy}
  use_object_mask: ${use_object_mask}
  use_negative_prompts: ${use_negative_prompts}
  cache_version: v2.2_test  # 测试集使用不同的缓存版本
  cache_mode: test
  batch_size: ${batch_size}
  num_workers: 16