name: sceneleap
mode: ${mode}

train:
  root_dir: /home/xiantuo/source/grasp/SceneLeap/data/test_final_test_520_1_processed
  succ_grasp_dir: /home/xiantuo/source/grasp/GithubClone/DexGraspBench/output/tabletop_objaverse_test_411_leap/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeap/data/object/objaverse_v1/flat_models
  max_grasps_per_object: 10
  mode: ${mode}
  batch_size: ${batch_size}
  num_workers: 16

val:
  root_dir: /home/xiantuo/source/grasp/SceneLeap/data/520_0_sub_15
  succ_grasp_dir: /home/xiantuo/source/grasp/GithubClone/DexGraspBench/output/tabletop_objaverse_test_411_leap/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeap/data/object/objaverse_v1/flat_models
  max_grasps_per_object: 1000
  mode: ${mode}
  batch_size: ${batch_size}
  num_workers: 16

test:
  root_dir: /home/xiantuo/source/grasp/SceneLeap/data/520_0_sub_15
  succ_grasp_dir: /home/xiantuo/source/grasp/GithubClone/DexGraspBench/output/tabletop_objaverse_test_411_leap/succ_collect
  obj_root_dir: /home/xiantuo/source/grasp/SceneLeap/data/object/objaverse_v1/flat_models
  max_grasps_per_object: 1000
  mode: ${mode}
  batch_size: ${batch_size}
  num_workers: 16
